apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/jkmancuso/misc
    targetRevision: HEAD
    path: nginx
  destination:
    name: "in-cluster"
    namespace: default